import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const user = await prisma.user.upsert({
    where: { vkUserId: 1 },
    update: {
      firstName: 'Ivan',
      lastName: 'Ivanov',
      avatarUrl: 'https://vk.com/images/camera_200.png',
      theme: 'LIGHT',
      tabOrder: JSON.stringify(['music', 'video', 'podcast', 'community', 'games', 'friends']),
    },
    create: {
      vkUserId: 1,
      firstName: 'Ivan',
      lastName: 'Ivanov',
      avatarUrl: 'https://vk.com/images/camera_200.png',
      theme: 'LIGHT',
      tabOrder: JSON.stringify(['music', 'video', 'podcast', 'community', 'games', 'friends']),
    },
  });

  await prisma.statistic.upsert({
    where: { userId: user.id },
    update: { views: 321, comments: 18, followers: 3, healthScore: 7791 },
    create: {
      userId: user.id,
      views: 321,
      comments: 18,
      followers: 3,
      healthScore: 7791,
    },
  });

  await prisma.contentItem.deleteMany();
  await prisma.contentItem.createMany({
    data: [
      // Music
      {
        type: 'MUSIC',
        title: 'Example Track 0',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Music+0',
        avatarUrl: 'https://placehold.co/100x100?text=M0',
        itemLink: 'https://vk.com/music',
        order: 0,
      },
      {
        type: 'MUSIC',
        title: 'Example Track 1',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Music+1',
        avatarUrl: 'https://placehold.co/100x100?text=M1',
        itemLink: 'https://vk.com/music',
        order: 1,
      },
      {
        type: 'MUSIC',
        title: 'Example Track 2',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Music+2',
        avatarUrl: 'https://placehold.co/100x100?text=M2',
        itemLink: 'https://vk.com/music',
        order: 2,
      },
      {
        type: 'MUSIC',
        title: 'Example Track 3',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Music+3',
        avatarUrl: 'https://placehold.co/100x100?text=M3',
        itemLink: 'https://vk.com/music',
        order: 3,
      },
      {
        type: 'MUSIC',
        title: 'Example Track 4',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Music+4',
        avatarUrl: 'https://placehold.co/100x100?text=M4',
        itemLink: 'https://vk.com/music',
        order: 4,
      },
      // Video
      {
        type: 'VIDEO',
        title: 'Example Video 0',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Video+0',
        avatarUrl: 'https://placehold.co/100x100?text=V0',
        itemLink: 'https://vk.com/video',
        order: 0,
      },
      {
        type: 'VIDEO',
        title: 'Example Video 1',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Video+1',
        avatarUrl: 'https://placehold.co/100x100?text=V1',
        itemLink: 'https://vk.com/video',
        order: 1,
      },
      {
        type: 'VIDEO',
        title: 'Example Video 2',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Video+2',
        avatarUrl: 'https://placehold.co/100x100?text=V2',
        itemLink: 'https://vk.com/video',
        order: 2,
      },
      {
        type: 'VIDEO',
        title: 'Example Video 3',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Video+3',
        avatarUrl: 'https://placehold.co/100x100?text=V3',
        itemLink: 'https://vk.com/video',
        order: 3,
      },
      {
        type: 'VIDEO',
        title: 'Example Video 4',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Video+4',
        avatarUrl: 'https://placehold.co/100x100?text=V4',
        itemLink: 'https://vk.com/video',
        order: 4,
      },
      // Podcasts
      {
        type: 'PODCAST',
        title: 'Example Podcast 0',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Podcast+0',
        avatarUrl: 'https://placehold.co/100x100?text=P0',
        itemLink: 'https://vk.com/podcasts',
        order: 0,
      },
      {
        type: 'PODCAST',
        title: 'Example Podcast 1',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Podcast+1',
        avatarUrl: 'https://placehold.co/100x100?text=P1',
        itemLink: 'https://vk.com/podcasts',
        order: 1,
      },
      {
        type: 'PODCAST',
        title: 'Example Podcast 2',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Podcast+2',
        avatarUrl: 'https://placehold.co/100x100?text=P2',
        itemLink: 'https://vk.com/podcasts',
        order: 2,
      },
      {
        type: 'PODCAST',
        title: 'Example Podcast 3',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Podcast+3',
        avatarUrl: 'https://placehold.co/100x100?text=P3',
        itemLink: 'https://vk.com/podcasts',
        order: 3,
      },
      {
        type: 'PODCAST',
        title: 'Example Podcast 4',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Podcast+4',
        avatarUrl: 'https://placehold.co/100x100?text=P4',
        itemLink: 'https://vk.com/podcasts',
        order: 4,
      },
      // Communities
      {
        type: 'COMMUNITY',
        title: 'Example Community 0',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Community+0',
        avatarUrl: 'https://placehold.co/100x100?text=C0',
        itemLink: 'https://vk.com/public0',
        order: 0,
      },
      {
        type: 'COMMUNITY',
        title: 'Example Community 1',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Community+1',
        avatarUrl: 'https://placehold.co/100x100?text=C1',
        itemLink: 'https://vk.com/public1',
        order: 1,
      },
      {
        type: 'COMMUNITY',
        title: 'Example Community 2',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Community+2',
        avatarUrl: 'https://placehold.co/100x100?text=C2',
        itemLink: 'https://vk.com/public2',
        order: 2,
      },
      {
        type: 'COMMUNITY',
        title: 'Example Community 3',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Community+3',
        avatarUrl: 'https://placehold.co/100x100?text=C3',
        itemLink: 'https://vk.com/public3',
        order: 3,
      },
      {
        type: 'COMMUNITY',
        title: 'Example Community 4',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Community+4',
        avatarUrl: 'https://placehold.co/100x100?text=C4',
        itemLink: 'https://vk.com/public4',
        order: 4,
      },
      // Games
      {
        type: 'GAME',
        title: 'Example Game 0',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Game+0',
        avatarUrl: 'https://placehold.co/100x100?text=G0',
        itemLink: 'https://vk.com/games',
        order: 0,
      },
      {
        type: 'GAME',
        title: 'Example Game 1',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Game+1',
        avatarUrl: 'https://placehold.co/100x100?text=G1',
        itemLink: 'https://vk.com/games',
        order: 1,
      },
      {
        type: 'GAME',
        title: 'Example Game 2',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Game+2',
        avatarUrl: 'https://placehold.co/100x100?text=G2',
        itemLink: 'https://vk.com/games',
        order: 2,
      },
      {
        type: 'GAME',
        title: 'Example Game 3',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Game+3',
        avatarUrl: 'https://placehold.co/100x100?text=G3',
        itemLink: 'https://vk.com/games',
        order: 3,
      },
      {
        type: 'GAME',
        title: 'Example Game 4',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Game+4',
        avatarUrl: 'https://placehold.co/100x100?text=G4',
        itemLink: 'https://vk.com/games',
        order: 4,
      },
      // Friends
      {
        type: 'FRIEND',
        title: 'Example Friend 0',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Friend+0',
        avatarUrl: 'https://placehold.co/100x100?text=F0',
        itemLink: 'https://vk.com/id0',
        order: 0,
      },
      {
        type: 'FRIEND',
        title: 'Example Friend 1',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Friend+1',
        avatarUrl: 'https://placehold.co/100x100?text=F1',
        itemLink: 'https://vk.com/id1',
        order: 1,
      },
      {
        type: 'FRIEND',
        title: 'Example Friend 2',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Friend+2',
        avatarUrl: 'https://placehold.co/100x100?text=F2',
        itemLink: 'https://vk.com/id2',
        order: 2,
      },
      {
        type: 'FRIEND',
        title: 'Example Friend 3',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Friend+3',
        avatarUrl: 'https://placehold.co/100x100?text=F3',
        itemLink: 'https://vk.com/id3',
        order: 3,
      },
      {
        type: 'FRIEND',
        title: 'Example Friend 4',
        subtitle: 'subtitle',
        coverUrl: 'https://placehold.co/200x200?text=Friend+4',
        avatarUrl: 'https://placehold.co/100x100?text=F4',
        itemLink: 'https://vk.com/id4',
        order: 4,
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
